name: Build Firmware

on:
  push:
    paths:
      - '**/*.ino'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compilar Sketch
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: esp32:esp32:d32
          platforms: |
            - name: esp32:esp32
              source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
              version: 3.3.11
          libraries: |
            - name: "WiFiManager@2.0.17"
            - name: "AsyncTelegram2@2.3.4"
            - name: "ArduinoJson@6.21.6"
          sketch-paths: |
            - .
          enable-deltas-report: true
          enable-warnings-report: true
          cli-compile-flags: |
            --export-binaries
            --output-dir=./build

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.sha }}
          path: build/**/*.bin
          if-no-files-found: error
