name: Build Firmware

on:
  push:
    branches:
      - main
    paths:
      - 'NetworkMonitor.ino'
      - '.github/workflows/build.yml'
  
  pull_request:
    branches:
      - main
    paths:
      - 'NetworkMonitor.ino'
      - '.github/workflows/build.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.3
        with:
          fqbn: esp32:esp32:d32
          platforms: |
            - name: esp32:esp32
              source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
              version: 3.3.11
          libraries: |
            - name: WiFiManager
              version: 2.0.17
            - name: AsyncTelegram2
              version: 2.3.4
            - name: ArduinoJson
              version: 6.21.6
          sketch-paths: |
            - .
          enable-deltas-report: true
          enable-warnings-report: true
